---
kind: Service
apiVersion: v1
metadata:
  name: my-angular-app 
spec:
  selector:
    app: my-angular
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 4200
      # Port to forward to inside the pod
      targetPort: 4200
      # Port accessible outside cluster
      #angularPort: 30567
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-angular-app-deploy
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: my-angular
    spec:
      containers:
        - name: my-angular-app-container 
          image: dhaneshande/angularsample
          ports:
            - containerPort: 4200
